version: '3.8'

services:
  web:
    image: crpi-3tfl0k0l13ezauo6.cn-beijing.personal.cr.aliyuncs.com/mtd-p/mtd:latest
    command: gunicorn --bind 0.0.0.0:8000 WEB_APP.wsgi:application
    volumes:
      - .:/app
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=WEB_APP.settings
      - TZ=Asia/Shanghai
    depends_on:
      - redis
      - celery

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./WEB_APP/static:/app/WEB_APP/static
      - ./WEB_APP/media:/app/WEB_APP/media
    depends_on:
      - web

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    image: crpi-3tfl0k0l13ezauo6.cn-beijing.personal.cr.aliyuncs.com/mtd-p/mtd:latest
    command: celery -A WEB_APP worker -l INFO
    volumes:
      - .:/app
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=WEB_APP.settings
      - TZ=Asia/Shanghai
    depends_on:
      - redis

volumes:
  redis_data: