# Generated by Django 4.2.18 on 2025-04-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MTD", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasetmanagement",
            name="category",
            field=models.CharField(
                choices=[
                    ("PCAP", "原始网络流量"),
                    ("CSV", "CSV格式"),
                    ("GRAY", "灰度图格式"),
                    ("RGB", "RGB图格式"),
                    ("OTHER", "其他"),
                ],
                default="OTHER",
                max_length=10,
                verbose_name="数据集类别",
            ),
        ),
        migrations.AlterField(
            model_name="modelmanagement",
            name="category",
            field=models.CharField(
                choices=[
                    ("CNN", "卷积神经网络"),
                    ("RNN", "循环神经网络"),
                    ("LSTM", "长短期记忆网络"),
                    ("TCN", "时间卷积网络"),
                    ("BiLSTM", "双向长短期记忆网路"),
                    ("BiTCN", "双向时间卷积网络"),
                    ("Deep_Learning", "深度学习模型"),
                    ("Machine_Learning", "机器学习模型"),
                    ("Stacking_Learning_Model", "集成学习模型"),
                    ("DMSE", "多堆叠集成模型"),
                    ("OTHER", "其他，详情见描述"),
                ],
                default="OTHER",
                max_length=100,
                verbose_name="模型类别",
            ),
        ),
    ]
