# Generated by Django 3.2.15 on 2025-04-10 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MTD', '0002_alter_datasetmanagement_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAugmentationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField()),
                ('log_file_path', models.FilePathField()),
                ('model_path', models.FilePathField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('stopped', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
