# Generated by Django 3.2.15 on 2025-04-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTD', '0004_alter_dataaugmentationtask_log_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionhistory',
            name='F1_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='F1分数'),
        ),
        migrations.AddField(
            model_name='detectionhistory',
            name='FPR',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='假阳率'),
        ),
        migrations.AddField(
            model_name='detectionhistory',
            name='TPR',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='真阳率'),
        ),
        migrations.DeleteModel(
            name='DataAugmentationTask',
        ),
    ]
