# Generated by Django 3.2.15 on 2025-04-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTD', '0005_auto_20250411_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='detectionhistory',
            name='is_malicious',
            field=models.BooleanField(default=False, verbose_name='是否含有恶意流量'),
        ),
        migrations.AlterField(
            model_name='modelmanagement',
            name='category',
            field=models.CharField(choices=[('CNN', '卷积神经网络'), ('RNN', '循环神经网络'), ('LSTM', '长短期记忆网络'), ('TCN', '时序卷积网络'), ('BiLSTM', '双向长短期记忆网路'), ('BiTCN', '双向时序卷积网络'), ('Deep_Learning', '深度学习模型'), ('Machine_Learning', '机器学习模型'), ('Stacking_Learning_Model', '集成学习模型'), ('DMSE', '多堆叠集成模型'), ('OTHER', '其他，详情见描述')], default='OTHER', max_length=100, verbose_name='模型类别'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
