# Generated by Django 3.2.15 on 2025-06-18 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MTD', '0006_auto_20250412_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(choices=[('CIC_IDS', 'CIC_IDS'), ('CTU', 'CTU'), ('USTC-TFC2016', 'USTC-TFC2016'), ('Botnet2014', 'Botnet2014')], max_length=20)),
                ('source_location', models.CharField(max_length=100)),
                ('target_location', models.CharField(max_length=100)),
                ('attack_value', models.FloatField()),
                ('attack_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('severity', models.CharField(default='medium', max_length=20)),
            ],
            options={
                'db_table': 'attack_records',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AttackStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('total_attacks', models.IntegerField(default=0)),
                ('unique_sources', models.IntegerField(default=0)),
                ('unique_targets', models.IntegerField(default=0)),
                ('max_attack_value', models.FloatField(default=0.0)),
                ('avg_attack_value', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'attack_statistics',
                'unique_together': {('dataset', 'date')},
            },
        ),
    ]
