# Generated by Django 3.2.15 on 2026-01-12 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MTD', '0007_attackrecord_attackstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file_share/', verbose_name='文件')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size', models.CharField(max_length=50, verbose_name='文件大小')),
                ('file_type', models.CharField(max_length=50, verbose_name='文件类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '文件共享',
                'verbose_name_plural': '文件共享',
                'ordering': ['-upload_time'],
            },
        ),
        migrations.DeleteModel(
            name='AttackRecord',
        ),
        migrations.DeleteModel(
            name='AttackStatistics',
        ),
    ]
